spring:
  datasource:
    url: jdbc:h2:mem:personality-test
    driver-class-name: org.h2.Driver
    username: teamway
    password: teamway
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
